---
title: "A short introduction to Data Science and R"
author: "MSc J. Manuel Magana Arias"
date: "Summer 2018"
output: html_document
---

## A short introduction to Data Science and R

There is not a formal definition for **Data Science**, however it can be seen as the intersection between statistics, computer science and any knowledge domain that demands analysis of big volumes of information such as Banking, Finance, Economics, Genomics, Astronomics, etc.

Data Science implies not only the extraction, preparation and analysis of massive data sets but also covers statistical modeling and data visualization tools that provide the business with more and better insights.

Successful data-driven companies apply Data Science to manage their business every day. Those organisations combine a variety of internal and external data sources in an analytics engine, translate the information into quantifiable and actionable insights to do real-time decision making that impact every level of the organization. As you can imagine, in order to achive this, companies have to make use of computers and programs that leverage the power of what we now call *Machine learning algorithms*, which is what this book is about, however in order to discuss the basics of those algorithms, we will need first to review the fundamentals of Statistics and computer programming.

In order to get a computer to do something, you have to *tell* it what you want in a series of instructions. These series of instructions are what we call a *computer program*.

In the same way that we, humans, communicate with each other using a specific language such as English, Spanish or French, computers also communicate (unconsciously) with other computers and human beings through the use of a *programming language*. All computer programs are written in a *programming language*. 

Programming languages vary a lot, and there are many of them, some are more intuitive than others, and not all of them serve the same purpose. For example, some programming languages such as *PHP* are ideal to create dynamic web pages, some others like *C* and *C++* are great for robotics and to automate industrial processes, while others are better to create quantitative algorithms for Statistics, Finance and Economics, the language we will use in this text is one of those and is named *R*.


*R* is one the more popular programming languages in Data Science, the other one worth to learn is *Python*. Both are open and free software, which means you can create, modify and share any program coded in those languages for free. There is no need to pay any license fee. 

*R* is a modern implementation of another computer language named *S*, in other words, *S* is the predecesor of *R*. The *S* language was developed by John Chambers and others at the Bell Laboratories, the historic laboratory created by Alexander Graham Bell in the 19th century as a research and scientific development company. During most the 20th century the Bell Labs formed part of AT&T until 1996, when it was owned by Alcatel-Lucetel which was later acquired by Nokia in 2016. The first version of *S* was created in 1976, it was aimed to be a statistical computing language with a more interactive approach than other existing languages such as *Fortran*, developed by IBM.

Ross Ihaka and Robert Gentleman, both Professors of Statistics at the University of Auckland in New Zealand, started working in the very first version of *R* in 1992, it took three years of work to release the first functional version in 1995. Nowadays, the most fundamental *R* packages are maintained and updated by a group of developers called the **R Development Core Team**, of which John Chambers is a member.

*R* works in a package framework, every package comes with a number of functions that you can use, modify and improve. That means that there are certain **base packages** such as `stats`,`graphics`, `utils`, `Matrix`, `boot` and `codetools` that provide you with the basic *R* functions. All the *base packages* are mantained by the *R Development Core Team*, however there are many other interesting packages developed by other people, mainly by Research Professors, that you can download and use freely. To clarify, the *base packages* are what you get when you download *R* the first time, however all the other packages are also available for you. We will explain how to do this in the next workshop. This package framework is exactly what makes *R* so popular and highly extensible!

As mentioned before, *R* includes a variety of packages for statistical analysis, linear and nonlinear modelling, classical statistical tests, etc. It also provides a mean for time-series analysis and packages that will allow your to explore the basics of Machine Learning such as classification and clustering analysis. *R* is also very powerful in terms of data visualisation and graphics. The `ggplot` package is an example of this.