---
title: "Data Science Handbook"
author: "MSc J. Manuel Magana Arias, PhD Alberto Dorantes"
date: "Summer 2018"
output: html_document
---

## Data Science Handbook

Welcome to the 'Data Science Handbook' project. 

This is the very first version of a collection of notes aimed to capture the basics of the methods and techniques from the areas of Predictive Analytics and Data Science. We focus on the domains of Finance and Econometrics. We employ **R** language to code all our sample scripts.

### Outline

### Part I - Introduction

#### [1.1 A short introduction to Data Science and R](https://github.com/jmagan01/DataScienceHandbook/blob/master/1.1%20A%20short%20introduction%20to%20Data%20Science%20and%20R.Rmd)

### Part II - Statistics

#### 2.1 Basic Statistics

#### 2.2 Normal Distribution

#### 2.2 Hypothesis testing

#### 2.3 Linear regression

#### 2.4 Introduction to Time Series

### Part III - Machine Learning

#### 3.1 Multiple regression

#### 3.2 Multicollienarity

#### [3.3 Logistic regression](https://github.com/jmagan01/DataScienceHandbook/blob/master/2.3%20Logistic%20regression.Rmd)

#### 3.4 Cross Validation

#### 3.5 Decision Trees

#### 3.6 Resampling methods: Bootstrapping & Bagging

#### 3.7 Support Vector Machines

#### 3.8 Clustering methods

#### 3.9 Dimension Reduction methods

### Part IV - Data Science applications

#### 4.1 Introduction to Big Data Applications

#### 4.2 Databases, Datawarehousing & Data Lakes

#### 4.2 Introduction to Data Visualisation

### Annex

#### [Setting up R and RStudio](https://github.com/jmagan01/DataScienceHandbook/blob/master/Setting%20up%20R%20and%20RStudio.Rmd) 

